### ISSUE TITLE
[Task]Minutiae Feature extraction Part 1

### ISSUE THREAD

**Issue by internet-zero** [archethic-foundation/biometrics-seed-extraction#10]
### Solution
- [x] 1. Study the architecture of MinutiaeNet (https://github.com/luannd/MinutiaeNet OR https://github.com/khaihp98/minutiae)
- [x] 2. get the testing and training data ready
- [x] 3. Minutiae extraction by "Thinned Binarized Method" & result analysis.
- [x] 4. explore "finger feature extractor" library  
- [x] 5. code implementation of "finger feature extractor library"
- [x] 6. Results comparison

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics-seed-extraction/10?planning-poker) with ZenHub @sauravkr-diat-ai @lucy-sha512 @nilesh-uniris

**Comment by I-Archer-Zero** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics-seed-extraction/10?planning-poker) with ZenHub @I-Archer-Zero
