### ISSUE TITLE
Finger print extraction (Part 4/8): ATECC608A Development With Cryptoauthlib - Configuration Zone and Slot Policies

### ISSUE THREAD

**Issue by lucy-sha512** [archethic-foundation/biometrics-seed-extraction#18]
### Problem
ATECC608A has a total of 16 slots for storing cryptographic keys used for symmetric as well as asymmetric operations. These slots have niche functionalities defined in the configuration zone of ATECC608A EEPROM.  Any changes in the configuration are nonwritable and it needs special privileges to do so. A clear understanding of configuration zone and slot policies is recommended before overwriting any keys on ATECC608a because some of the operations may be irreversible.

#### Access the Configuration Zone
- [x]  Understanding Configuration Zone and Slot Policies:
-Update the documentation: https://misc.archethic.net/Ofge9a-_Tv2S3JDu97TTkA
- Before a CryptoAuthentication device may be used its configuration must be set for the intended use case.
- Configurations can be quite complex and need to be carefully created and analyzed for security gaps that could be introduced by an unintended configuration interaction. 
- the datasheet of ATECC608a has to be understood thoroughly before making any configuration changes.

-  Typical Configuration zone of an ATECC608a device is as follows:
Configuration Zone:
 01 23 43 C8 00 00 60 02 7D 60 FO 1C EE 01 6D 00 CO 00 00 00 83 20 87 20 8F 20 C4 8F BE 8F 8F 8F 9F 8F AF 8F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 AF 8F FF FF FF FF 00 00 00 00 FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 55 55 FF FF 00 00 00 00 00 00 33 00 33 00 33 00 1C 00 1C 00 1C 00 1C 00 1C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 1C 00 
- The above 128 bytes configuration zone data gives information about each slot and its policies.
- There is a need for understanding the data in this configuration zone so that slot policies can be modified to support functionalities like Signing, verification and attestation.
- [x]  View Configuration Zone with cryptoauthapi
- CryptoauthlibAPI could be used to view the default configuration zone before making any changes.
- The default configuration of ATECC608a is different hence lock status of the config zone have to be modified to do any changes.

- [x] Change features of the Configuration Zone according to the fingerprint software requirements (if required)

**Comment by lucy-sha512** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics-seed-extraction/18?planning-poker) with ZenHub @internet-zero @nilesh-uniris @sauravkr-diat-ai

**Comment by AmodD** [comment]
moving to closed as we discussed that reviewing is not possible
