### ISSUE TITLE
[Task]: Thorough study of Fingerprint feature extraction, their challenges involved

### ISSUE THREAD

**Issue by I-Archer-Zero** [archethic-foundation/biometrics-seed-extraction#9]
### Solution

Study of 3 features of the fingerprint
- [x] Patterns
- [x] Minutiae
- [x] Pores and Ridges 
- [x] Possibility/Suggestions: The already existing algorithms for all the above 3 types of features

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics-seed-extraction/9?planning-poker) with ZenHub @lucy-sha512 @sauravkr-diat-ai @I-Archer-Zero @nilesh-uniris

**Comment by sauravkr-diat-ai** [comment]
The study involves
i. **Fingerprint analysis** 
ii. **Method to extract Fingerprint features** : It focus on conventional image processing method & AI methods. Their advantages & disadvantages.
iii. **Sensor Study** : It refers to the device which is used for input of fingerprint. It can be optical, capacitive or ultrasonic. 

Resources/ Refrences:
https://www.researchgate.net/publication/247773759_Fingerprint_Recognition_System_Design_Analysis

https://link.springer.com/book/10.1007/978-1-84882-254-2

https://link.springer.com/referenceworkentry/10.1007/978-0-387-73003-5_50
